apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nnsplitrequests.my-group.example.com
spec:
  group: my-group.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                input: 
                  type: string
                output: 
                  type: string
          required:
            - spec
  scope: Namespaced
  names:
    plural: nnsplitrequests
    singular: nnsplitrequest
    kind: NNSplitRequest
    shortNames:
      - nnsr
