apiVersion: v1
kind: ServiceAccount
metadata:
  name: nnsplitrequest-watcher
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nnsplitrequest-watcher-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: nnsplitrequest-watcher
  namespace: default
roleRef:
  kind: Role
  name: nnsplitrequest-watcher
  apiGroup: rbac.authorization.k8s.io
