apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nnsplitrequests.my-group.example.com
spec:
  group: my-group.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                job_id:
                  type: integer
                user:
                  type: integer
                num_gpu:
                  type: integer
                num_cpu:
                  type: integer
                num_ram:
                  type: integer
                duration:
                  type: string
                job_name:
                  type: string
                submit_time:
                  type: integer
                gpu_type:
                  type: string
                num_inst:
                  type: integer
                size:
                  type: string
                read_count:
                  type: integer
  scope: Namespaced
  names:
    plural: nnsplitrequests
    singular: nnsplitrequest
    kind: NNSplitRequest
    shortNames:
      - nnsr

