apiVersion: my-group.example.com/v1
kind: NNSplitRequest
metadata:  
  name: example-nnsplitrequest
  namespace: default
spec:
  job_id: 0
  user: 0
  num_gpu: 0
  num_cpu: 4
  num_ram: 3
  duration: "120"
  job_name: "example-job"
  submit_time: 123456 
  gpu_type: "NVIDIA Tesla V100"
  num_inst: 2
  size: "1GB"
  read_count: 100
